project:
  type: website

website:
  title: "R Census Examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tidycensus.qmd
        text: tidycensus
      - href: choroplethr.qmd
        text: choroplethr
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

